### ISSUE TITLE
LoginActvity throws an IllegalStateException if the requested permission list id empty

### ISSUE THREAD

**Issue by msh91** [tinode/android-example#8]
this is the logcat report:

`08-25 12:46:03.121 5264-5264/co.tinode.tindroid E/AndroidRuntime: FATAL EXCEPTION: main
    Process: co.tinode.tindroid, PID: 5264
    java.lang.RuntimeException: Unable to start activity ComponentInfo{co.tinode.tindroid/co.tinode.tindroid.LoginActivity}: java.lang.IllegalArgumentException: permission cannot be null or empty
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.IllegalArgumentException: permission cannot be null or empty
        at android.content.pm.PackageManager.buildRequestPermissionsIntent(PackageManager.java:3544)
        at android.app.Activity.requestPermissions(Activity.java:4381)
        at android.support.v4.app.ActivityCompat.requestPermissions(ActivityCompat.java:507)
        at co.tinode.tindroid.LoginActivity.requestPermissions(LoginActivity.java:152)
        at co.tinode.tindroid.LoginActivity.onCreate(LoginActivity.java:117)
        at android.app.Activity.performCreate(Activity.java:7009)
        at android.app.Activity.performCreate(Activity.java:7000)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)`

**Comment by msh91** [comment]
I fixed the issue and create this [pull request](https://github.com/tinode/android-example/pull/9)

**Comment by or-else** [comment]
Great catch, thanks!

If you don't mind, please read the CLA and fill out the form: https://github.com/tinode/chat/blob/master/docs/CLA.md

See here why we ask for it:
https://github.com/tinode/chat/blob/master/CONTRIBUTING.md#why-is-the-contributor-license-agreement-necessary

Thanks again.

**Comment by msh91** [comment]
@or-else 
I have signed it
